# This is a basic workflow to help you get started with Actions

name: 下载

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      video-url:
        default: BVXXX
        type: string
        required: true
      cookie:
        type: string
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 安装 ffmpeg
        run: sudo apt-get install ffmpeg -y
      - name: 设置 python 3.9
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'
      - name: 安装 Yutto
        run:
          pip install --pre yutto
      - name: 下载视频
        run: |
          mkdir video
          cd video && yutto ${{ inputs.video-url }} -c "${{ inputs.cookie }}" --with-metadata
      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: video
